### ISSUE TITLE
MacOS support 🙏

### ISSUE THREAD

**Issue by Asavarkhul** [miciwan/PaintMixing#1]
Hey there! 

Thanks for this impressive work and very interesting investigation.

What could be the effort for providing MacOS support as mentioned in your introduction?

Many thanks!

**Comment by miciwan** [comment]
I created a MacOS .dmg file with what PyInstaller created, and it seems to work. Give it a try!

**Comment by brydoncheyney** [comment]
> I created a MacOS .dmg file with what PyInstaller created, and it seems to work. Give it a try!

Let me get to my non-work laptop... _trust issues_ 👍 certainly, the PR was validated on an M1 Mac 😄
